version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build:
    executor: win/default

    steps:
      - run:
          name: Display SSH Key
          command: |
            if [[ -f ~/.ssh/id_rsa ]]; then
              echo "SSH key exist"
              ls -l ~/.ssh/id_rsa
            else
              echo "SSH key not found"
            fi
      - checkout
      - run: dotnet build
      - run: dotnet test