version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build:
    executor: win/default

    steps:
      - run:
          name: Display SSH Key
          command: |
            if (test -f ~/.ssh/id_rsa); then
              echo "SSH Key Exists"
              ls -l ~/.ssh/id_rsa
            else
              echo "SSH Key Not Found"
            fi
      - checkout
      - run: dotnet build
      - run: dotnet test