version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - run:
        name = Display SSH Key
        command: cat ~/.ssh/id_rsa
      - checkout
      - run: dotnet build
      - run: dotnet test